services:
  - type: web
    name: stevara-frontend
    runtime: static
    rootDir: web
    buildCommand: pnpm install && pnpm build
    staticPublishPath: out
    pullRequestPreviewsEnabled: true
    headers:
      - path: /_next/static/**
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /
        name: Cache-Control
        value: public, max-age=0, must-revalidate
